"""
This is a setup.py script generated by py2app

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["stock_monitor/ui/menubar.py"]
DATA_FILES = []
OPTIONS = {
    "argv_emulation": True,
    "plist": {
        "LSUIElement": True,
        "CFBundleName": "Stock Monitor",
        "CFBundleDisplayName": "Stock Monitor",
        "CFBundleIdentifier": "com.stockmonitor.app",
        "CFBundleVersion": "1.0.0",
        "CFBundleShortVersionString": "1.0.0",
    },
    "packages": ["rumps", "requests", "matplotlib", "numpy"],
}

setup(
    name="Stock Monitor",
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
    install_requires=[
        "rumps",
        "requests",
        "matplotlib",
        "numpy",
    ],
)
